---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-KONFLUX-15169_e2e_fail_on_grafana
