---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-KONFLUX-15169_e2e_fail_on_grafana
