---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-KAR-967_migrate_service-ca_cert-manager_dev
