---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-dev_update_otel_collector_to_01530
