---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-KAR-896_force_auth_for_gateway_development
