---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/olegbet/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-KONFLUX-14972_api-server_OOM_dev
