apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vector-kubearchive-log-collector
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/vector-kubearchive-log-collector
                environment: staging
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: vector-kubearchive-log-collector-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/olegbet/infra-deployments.git
        targetRevision: KONFLUX-8225_add_log_forwarder_for_loki
      destination:
        namespace: product-kubearchive-logging
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
