apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki
name: loki
repo: https://grafana.github.io/helm-charts
version: 0.0.1
releaseName: vector-kubearchive-logs-collector
namespace: kubearchive-logging
valuesFile: loki-helm-values.yaml