apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-kubearchive-logging
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
  ignore-check.kube-linter.io/drop-net-raw-capability: |
    "Vector Runs requires access to socket."
  ignore-check.kube-linter.io/run-as-non-root: |
    "Vector Runs as Root and attach host Path."
  ignore-check.kube-linter.io/sensitive-host-mounts: |
    "Vector Runs requires certain host mounts to watch  files being created by pods."

generators:
- vector-helm-generator.yaml

resources:
- vector-pre.yaml
