apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vector
name: vector
repo: https://helm.vector.dev
version: 0.46.1
releaseName: vector-kubearchive-logs-collector
namespace: kubearchive-logging
valuesFile: vector-helm-values.yaml
