apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-id-config
  namespace: product-kubearchive-logging
data:
  # This will be updated by the cluster-id-update-job
  CLUSTER_ID: "development-cluster"
