apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: minio
name: minio
repo: https://charts.bitnami.com/bitnami
version: 16.0.10
releaseName: vector-kubearchive-log-collector
namespace: product-kubearchive-logging
valuesFile: minio-helm-values.yaml

