apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: minio
name: minio
repo: https://charts.bitnami.com/bitnami
version: 0.0.1
releaseName: vector-kubearchive-log-collector
namespace: product-kubearchive-logging
valuesFile: minio-helm-values.yaml
