apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- loki-secret.yaml

generators:
- loki-helm-generator.yaml
- grafana-helm-generator.yaml

patches:
- patch: |-
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: kubearchive-loki
      namespace: product-kubearchive-logging
    spec:
      dataFrom:
        - extract:
            key: staging/kubearchive/loki
      refreshInterval: 5m
      secretStoreRef:
        kind: ClusterSecretStore
        name: appsre-stonesoup-vault
      target:
        creationPolicy: Orphan
        name: kubearchive-loki
        template:
          metadata:
            annotations:
              argocd.argoproj.io/sync-options: Prune=false
