# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
loki:
  # Explicit image configuration to fix ErrImagePull - using Docker Hub registry
  image:
    repository: grafana/loki
    tag: "3.3.0"
    pullPolicy: IfNotPresent
  
  limits_config:
    max_query_length: 0
  auth_enabled: true
  basic_auth:
    enabled: true
    existingSecret: kubearchive-loki
  storage:
    type: s3
    s3:
      region: us-east-1
      type: "aws_s3"
    bucketNames:
      chunks: stone-stg-rh01-loki-storage
      ruler: stone-stg-rh01-loki-storage
      admin: stone-stg-rh01-loki-storage

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  commonConfig:
    replication_factor: 1

  compactor:
    retention_enabled: true
    delete_request_store: s3
  ruler:
    storage:
      type: s3
      s3:
        bucketNames:
          ruler: stone-stg-rh01-loki-storage

deploymentMode: SingleBinary

# Gateway configuration to fix DNS resolver
gateway:
  enabled: true
  replicas: 1
  # Explicit gateway image configuration - using Docker Hub registry
  image:
    repository: nginx
    tag: "1.24-alpine"
    pullPolicy: IfNotPresent
  nginxConfig:
    resolver: dns-default.openshift-dns.svc.cluster.local

# Configure ServiceAccount for Loki
serviceAccount:
  create: false  # We create it manually in loki-pre.yaml
  name: loki-sa

# OpenShift-compatible security context
securityContext:
  runAsNonRoot: false  # Allow running as root for loki
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsNonRoot: false  # Allow running as root for loki
  allowPrivilegeEscalation: false

containerSecurityContext:
  runAsNonRoot: false  # Allow running as root for loki
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

# Disable canary to avoid SCC issues for now
lokiCanary:
  enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki
  extraVolumes:
    - name: loki-storage
      emptyDir: {}

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Disable memory-intensive caching for development environment  
chunksCache:
  replicas: 0  # Scale to 0 replicas to avoid memory issues

resultsCache:
  enabled: true
  allocatedMemory: 256  # Keep results cache but with minimal memory
  # Explicit image for results cache - using Docker Hub registry
  image:
    repository: memcached
    tag: "1.6.24-alpine"
    pullPolicy: IfNotPresent

# Disable test pods for cleaner development environment  
test:
  enabled: false
