# Simplified Loki configuration for staging
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # Storage configuration required by the helm chart
  storage:
    type: s3
    bucketNames:
      chunks: stone-stg-rh01-loki-storage
      ruler: stone-stg-rh01-loki-storage
      admin: stone-stg-rh01-loki-storage
    s3:
      endpoint: https://s3.us-east-1.amazonaws.com
      region: us-east-1
      bucketNames:
        chunks: stone-stg-rh01-loki-storage
        ruler: stone-stg-rh01-loki-storage
        admin: stone-stg-rh01-loki-storage

  storage_config:
    aws:
      region: us-east-1
      bucketnames: stone-stg-rh01-loki-storage

  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki

  compactor:
    retention_enabled: true
    delete_request_store: s3
    working_directory: /var/loki/compactor
  
  ruler:
    storage:
      type: s3
      s3:
        bucketNames:
          ruler: stone-stg-rh01-loki-storage

deploymentMode: SingleBinary

# Gateway configuration
gateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Pod and container security contexts
podSecurityContext:
  runAsNonRoot: false  # Allow running as root for loki
  allowPrivilegeEscalation: false

containerSecurityContext:
  runAsNonRoot: false  # Allow running as root for loki
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

# Disable canary to avoid SCC issues for now
lokiCanary:
  enabled: false

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    enabled: false
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki
  extraVolumes:
    - name: loki-storage
      emptyDir: {}

# Disable sidecar completely
sidecar:
  rules:
    enabled: false
  datasources:
    enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Disable ALL memcached components
chunksCache:
  enabled: false
  replicas: 0

resultsCache:
  enabled: false
  replicas: 0

memcached:
  enabled: false

memcachedResults:
  enabled: false

memcachedChunks:
  enabled: false

memcachedFrontend:
  enabled: false

memcachedIndexQueries:
  enabled: false

memcachedIndexWrites:
  enabled: false

# Disable test pods for cleaner development environment  
test:
  enabled: false
